package ics4x.storedatabase;
/*
 * Assignment Name: [ShoppingList]
 * Class Name: [Toy]
 * Author: [Shaiza Hashmi]
 * Date: [11/25/2018]
 * Description: [This class extends superclass item and implements the interface of Taxable. This class generate the
 *               appropriate and necessary values for the Toys category. Description, Prices, and age limits are information
 *               included and generated here]
 */

public class Toy extends Item implements Taxable{


    private double[] toyPrice = new double[3];//overrides superclass' variable
    private int[] age = new int[4]; //array to hold the ages generated by the random number generator

    public void generatePrices(){   //generates prices for toys from a set interval
        for(int i = 0; i <3; i++){
            toyPrice[i] = rand.nextFloat() * (25.0 - 10.0) + 10.0;
            //inventory[i][2] = String.format ("%.2f", toyPrice[i]);
            calculateTax();
        }
    }

    public void calculateTax(){
        for(int i = 0; i < 3; i++){
            toyPrice[i] = toyPrice[i]* taxRate;
            inventory[i][2] = String.format ("%.2f", toyPrice[i]);
        }
    }

    public void descriptions(){ //generates the decriptions/names of all toys
        inventory[0][0] = "Toy Car";
        inventory[1][0] = "Doll";
        inventory[2][0] = "Lego";
    }

    public void quantity(){
        super.quantity();
    }//calls super's method

    public void ages(){//generates the youngest age limit for children in order to play
        for(int i = 0; i < 3; i++){
            age[i] = rand.nextInt(10-3) + 3;
            inventory[i][3] = (Integer.toString(age[i]) + "+");
        }
    }
}
